export {default as Home} from './Home'
export {default as Login} from './Login'
export {default as Welcome} from './Welcome'
export {default as SignUp} from './SignUp'
export {default as NotFound} from './NotFound'
export {default as Details} from './Details'
export {default as Actor} from './Actor'
export {default as Director} from './Director'
export {default as MyList} from './MyList'
export {default as ShowsList} from './ShowsList'

